[package]
name = "lava"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
glam = {workspace = true}
anyhow = {workspace = true}
bytemuck = {workspace = true}
tracing = {workspace = true}
ash = {workspace = true}
ash-window = {workspace = true}
gpu-allocator = {workspace = true}
raw-window-handle = {workspace = true}
lava-macros = { version = "0.1.0", path = "../lava-macros" }
smallvec.workspace = true
notify = "8.2.0"

[build-dependencies]
shader-slang = { git = "https://github.com/FloatyMonkey/slang-rs" }

[features]
default = []
# hot-reload = ["notify"]
