[package]
name = "lava"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
ash = "0.38.0"
ash-window = "0.13.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
derivative = "2.2.0"
glam = { version = "0.30.5", features = ["bytemuck"] }
gpu-allocator = { version = "0.27", default-features = false, features = ["vulkan"] }
log = "0.4.28"
presser = "0.3.1"
winit = "0.30.12"

