[package]
name = "core"
version = "0.1.0"
build="build.rs"
edition = "2024"

[dependencies]
glam = { version = "0.30.5", features = ["bytemuck"] }
bevy = {version = "0.18.0", default-features = false, features = [
    "trace", 
    "debug",
    "detailed_trace",
    "wayland",
    "asset_processor", 
    "embedded_watcher", 
    "file_watcher", 
    "multi_threaded",
    "bevy_winit",
    "bevy_asset",
    "bevy_window",
]}

lava = { version = "0.1.0", path = "../lava" }
gpu-allocator = "0.27.0"
anyhow = "1.0.99"
gltf = "1.4.1"
tiff = "0.10.3"
smallvec = "1.15.1"
meshopt = "0.6.1"
bytemuck = { version = "1.24.0", features = ["derive"] }
bytemuck_derive = "1.10.2"
itertools = "0.14.0"
metis = "0.2.2"
rand = "0.9.2"
imgui = "0.12.0"
tracy-client = {version = "0.18.4", optional = true }
async-std = "1.13.2"
futures = "0.3.31"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "registry"] }
tracing-log = "0.2"   

[features]
default = []
trace = ["tracy-client", "bevy/trace_tracy", "lava/trace"]


[build-dependencies]
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"