[package]
name = "core"
version.workspace = true
build = "build.rs"
edition.workspace = true

[dependencies]
glam = {workspace = true}
bevy = {workspace = true}
anyhow = {workspace = true}
bytemuck = { workspace = true }

lava = { version = "0.1.0", path = "../lava" }

bytemuck_derive = {workspace = true}
gltf = {workspace = true}
smallvec = {workspace = true}
meshopt = {workspace = true}
itertools = {workspace = true}
metis = {workspace = true}
rand = {workspace = true}
async-std = {workspace = true}
futures = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
tracing-log = {workspace = true}
tracing-tracy = {workspace = true}
tracy-client = {workspace = true}
tracing-core = {workspace = true}
fontdue = {workspace = true}
ron = {workspace = true}
serde = {workspace = true}

[features]
default = []
dynamic_linking = ["bevy/dynamic_linking"]

[build-dependencies]
walkdir = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
